app/controllers/index.js
app/templates/index.hbs

This PR adds:
- Navigation controls
- Scale
- Geolocate

Map Controls

---

app/controllers/index.js
app/styles/layouts/_l-default.scss
app/templates/index.hbs

This PR tweaks the selector menu, making it more responsive for small screens, and adding active and hover styles.

Selector Menu

---

app/components/map-utility-box.js
app/styles/app.scss
app/styles/base/_typography.scss
app/styles/layouts/_l-default.scss
app/styles/modules/_m-search.scss
app/templates/components/map-utility-box.hbs
package-lock.json
package.json

This PR adds placeholder content for the map util box

Ac placeholder features

---

app/controllers/report.js
app/styles/base/_typography.scss
app/templates/report.hbs

report header with count, type, geoms list

---

app/styles/base/_typography.scss

add styles for active .menu.tabs

---

app/templates/components/map-utility-box.hbs

This PR put the "Clear Selection" button inside a check to see if there is a selection, so we only show it if there's something to clear.

show/hide .button--clear-selection if there's a selection

---

app/styles/base/_typography.scss
app/styles/layouts/_l-default.scss
app/templates/report.hbs

Closes #70 (which is already closed).

update report layout to include mode switcher

---

app/components/population-pyramid.js
app/controllers/report/demographic.js
app/styles/layouts/_l-default.scss
app/templates/components/population-pyramid.hbs
tests/integration/components/population-pyramid-test.js

This PR adds a static tooltip to the population pyramid, and cleans up the code.

Population Pyramid enhancements

---

app/controllers/report.js
app/styles/base/_typography.scss
app/styles/layouts/_l-default.scss
app/templates/report.hbs
app/templates/report/demographic.hbs

This PR adds all the table columns and adjusts the report mode buttons and also adds reliability and comparison buttons.

7 add all columns

---

app/styles/base/_typography.scss
app/templates/report.hbs

better mobile styles for .report-mode

---

app/templates/index.hbs

change order of .menu--selector

---

app/styles/base/_typography.scss
app/templates/report/demographic.hbs
app/templates/report/housing.hbs

add report headers

---

app/templates/components/demographic-change-table-row.hbs
app/templates/components/demographic-table-row.hbs

This PR updates the formula of percentage change and closes issue #147

updated the percent formula

---

app/controllers/report.js
app/templates/report.hbs

This PR updates selection button text to "Edit your Selection" and set current default view to hide reliability data by default, show comparison data by default. 
Close #136 #137

close 136 137 - update selection text and set current default view

---

app/components/population-pyramid.js

format pop pyramid tooltip percentages

---

app/layer-groups/census-blocks.js
app/layer-groups/census-tracts.js
app/layer-groups/neighborhood-tabulation-areas.js
app/layer-groups/nyc-pumas.js

uniform line colors for selectable geometries

---

app/components/acs-table.js
app/components/download-spreadsheet.js
app/mixins/downloadable.js
app/routes/report/demographic.js
app/routes/report/economic.js
app/routes/report/housing.js
app/routes/report/social.js
app/templates/components/acs-table-row.hbs
app/templates/components/download-spreadsheet.hbs
app/templates/components/report-header.hbs
app/templates/report/demographic.hbs
app/templates/report/economic.hbs
app/templates/report/housing.hbs
app/templates/report/social.hbs
tests/unit/mixins/downloadable-test.js

Fixes some download functionality by making it available for all reports; minor fixes to sorting of download; removes copy to clipboard;

146 dl for all

---

app/queries/report.js
app/templates/report/social.hbs

This PR fixes the divide by zero error that was causing two tables not to work in the social profile.  
Closes #138

add missing social profile data and tables

---

app/styles/base/_typography.scss

This PR lightens the `.row-highlight` color.

Row Highlight

---

app/templates/components/map-utility-box.hbs
package-lock.json

195 dynamic call to action

---

app/components/tab-dropdown.js
app/mixins/downloadable.js
app/services/scroller.js
app/styles/base/_typography.scss
app/styles/layouts/_l-default.scss
app/templates/components/profile-header.hbs
app/templates/components/tab-dropdown.hbs
app/templates/profile.hbs
app/templates/profile/demographic.hbs
app/templates/profile/economic.hbs
app/templates/profile/housing.hbs
app/templates/profile/social.hbs
package-lock.json
package.json
tests/integration/components/tab-dropdown-test.js

212 profile section nav

---

app/chart-config/housing/housing-tenure.js

This PR updates property value in chart config file.

fix bug due to variable name change in the database

---

app/templates/components/profile-header.hbs

@CeciliaCY Here's a fix for the wiggly checkbox bug you found.

use fix-width fa icons for profile header checkboxes

---

app/templates/profile/social.hbs

I think this fix will make the disability data appear.

Fix disability table-- not appearing

---

app/table-config/decennial/asian-subgroup.js
app/table-config/decennial/head-household.js
app/table-config/decennial/hisp-subgroup.js
app/table-config/decennial/household-size.js
app/table-config/decennial/household-type.js
app/table-config/decennial/housing-occupancy.js
app/table-config/decennial/housing-tenure.js
app/table-config/decennial/mutually-excl-race-hisp.js
app/table-config/decennial/tenure-age-householder.js
app/templates/profile.hbs
app/templates/profile/census.hbs

properly indent decenial tables, fix typos

---

app/styles/base/_typography.scss
app/templates/components/profile-header.hbs
app/templates/profile/census.hbs
app/templates/profile/demographic.hbs
app/templates/profile/economic.hbs
app/templates/profile/housing.hbs
app/templates/profile/social.hbs

210 nix quick facts

---

ember-cli-build.js

Disables auto-removal of “unused” icons, addon feature doesn’t work properly. This should fix the production issue
Closes 253

Fix ember-font-awesome bug

---

app/layer-groups/boroughs.js
app/layer-groups/choropleths.js
app/layer-groups/communitydistricts.js
app/layer-groups/index.js
app/layer-groups/neighborhood-tabulation-areas-selection.js
app/layer-groups/nyc-pumas-selection.js
app/layer-groups/nyc-pumas.js
app/layer-groups/nyccouncildistricts.js
app/sources/admin-boundaries.js
app/sources/choropleths.js
app/sources/index.js
app/styles/modules/_m-advanced-options.scss
app/templates/components/layer-menu-item.hbs
app/templates/components/map-utility-box.hbs
app/templates/index.hbs
app/utils/admin-boundary-styles.js
package-lock.json

This PR adds subways and various admin boundaries to the layergroup control palette under "Advanced Options".  Most was ported over from ZoLa, with some small styling tweaks.
Closes #5

5 overlay layers

---

app/queries/summary-levels.js
app/sources/admin-boundaries.js
app/sources/choropleths.js

exclude airports from NTA queries

---

app/services/selection.js

Add logic to hide basemap neighborhood labels when NTA selection mode is active
Closes #128

128 duplicate neighborhood labels

---

app/table-config/economic/ratio-of-income-to-poverty-level.js

properly highlight the Ratio of Income to Poverty Level table rows

---

app/components/profile-footer.js
app/styles/layouts/_l-default.scss
app/templates/components/profile-footer.hbs
app/templates/profile/census.hbs
app/templates/profile/demographic.hbs
app/templates/profile/economic.hbs
app/templates/profile/housing.hbs
app/templates/profile/social.hbs
tests/integration/components/profile-footer-test.js

add profile footer

---

app/templates/profile/demographic.hbs

re-add pop pyramid male/female header

---

app/layer-groups/choropleths.js

rename choropleths UI

---

app/templates/components/population-pyramid.hbs

Changed "estimate" to "percent" in chart legend

---

app/table-config/economic/income-and-benefits.js

Median nonfamily income

---

app/table-config/economic/employment-status.js

Updated label for unemployed in table

---

app/choropleth-config/index.js

lighten yellow in choropleth palette

---

app/choropleth-config/index.js

290 choropleth line color

---

app/styles/base/_typography.scss

make thead font slightly larger (nix crufty styles)

---

app/templates/profile/census.hbs

Moved population density to top of profile

---

app/components/comparison-area-selector.js
app/templates/components/comparison-area-selector.hbs

This PR updates the display labels for the comparison area selector dropdown
Closes #209

refactor comparison dropdown query for better labels

---

.eslintrc.js
app/components/data-table-row-change.js
app/models/row.js
app/templates/components/data-table-row-change.hbs
app/templates/components/data-table-row-current.hbs

This PR adds computed functions to the row model and the `data-table-row-change` controller to populate the missing values that we had placeholders for.
Closes #353 
Not ready to merge, should get a review from @EricaMaurer or @JoelAAlvarez first.

353 missing data

---

.eslintrc.js
app/components/data-table-row-change.js
app/models/row.js
app/queries/profile.js
app/templates/components/data-table-row-change.hbs
app/templates/components/data-table-row-current.hbs

This PR:
- Updates the logic for percent MOE calculations in ACS profiles, changes a + to a - to fix the data
- Adds some logic to prevent -0.0 from showing up in the comparison percent column
Closes #358
Closes #357

358 357 fixes

---

app/components/data-table-row-change.js
app/templates/components/data-table-row-change.hbs

Cw graying

---

app/table-config/housing/gross-rent.js

This PR adds configuration to correctly calculate the Median gross rent's coefficient of variance.

Median gross rent CV

---

app/table-config/demographic/sex-and-age.js
app/table-config/economic/earnings.js
app/table-config/economic/income-and-benefits.js
app/table-config/housing/rooms.js
app/table-config/housing/value.js

Median CVs

---

app/models/row.js

Fix difference MOE calculation

---

app/table-config/housing/housing-tenure.js

Fix for avghhsooc selected area and comparison area cv
Fix for avghhsooc comparison area sum

Fix avghhsooc

---

app/table-config/housing/housing-occupancy.js

Adds calculations for hovacrt and rntvacrt CVs

Calculations for hovacrt and rntvacrt cvs

---

app/components/data-table-row-change.js

Removed an extra '*1.645' from formula

Fix change number MOE

---

app/templates/about.hbs

Updated email address to pff_dl and changed weblink from zola to pff

Updated email address to pff_dl

---

app/table-config/decennial/sex-and-age.js

Variable was changed in database to 'Under 18 year' but wasn't updated in the code.
Closes issue #466

Changed variable name and label: population 18+ to under 18 years

---

app/table-config/economic/earnings.js

Updated design factor for all three earning medians

---

app/table-config/social/household-type.js

Two decimal places shown for avghhsz and avgfmsz

Fix decimal for avghhsz and avgfmsz

---

app/templates/profile/demographic.hbs
app/templates/profile/economic.hbs
app/templates/profile/housing.hbs
app/templates/profile/social.hbs

only show charts in current mode

---

app/templates/profile/social.hbs

Add note to Language sub-section title and add tooltip

---

README.md
app/templates/about.hbs
app/templates/components/site-header.hbs
app/templates/data.hbs

Change 'Population Fact Finder' to 'Population FactFinder'

---

app/table-config/decennial/household-type.js
app/table-config/decennial/population-density.js
package-lock.json

Closes #477 (once data has been updated).

fix indentation and highlighting of rows

---

app/templates/profile.hbs
app/templates/profile/census.hbs
app/templates/profile/demographic.hbs

Change 'Sex and Age' sub-section headers to 'Age and Sex'

---

app/templates/about.hbs

add MailChimp form to About

---

app/components/comparison-area-selector.js

order boros and pumas in typeahead

---

app/templates/features.hbs

add links to open data, open source sections of features page

---

app/helpers/render-top-bottom-coding-suffix.js
app/models/row.js
app/routes/profile/economic.js
app/templates/components/data-table-column-group.hbs
app/templates/components/data-table-row-change.hbs
app/templates/components/data-table-row-current.hbs
tests/integration/helpers/render-top-bottom-coding-suffix-test.js

This PR adds logic for showing a plus or minus when it's top or bottom coded.
Closes #157

Adds logic for hiding values based on top-bottom coding

---

app/styles/base/_typography.scss
app/templates/components/data-table-row-change.hbs
app/templates/components/data-table-row-current.hbs

This PR adds logic to show "Data are not available" in current view profiles when `sum` is null
Closes #474

Cw census data not available

---

app/templates/components/map-utility-box.hbs

remove duplicate thematic map list items

---

app/table-config/social/residence-1-year-ago.js

Fix indent settings for Residence 1 Year Ago table

---

app/adapters/row.js

made fetch happen on row adapter

---

app/table-config/decennial/relationship-to-head-of-household--householder.js
app/table-config/decennial/sex-and-age.js

- New Feature
- API change
Closes #465

Fix Under 18 data

---

app/components/data-table-row-change.js
app/components/data-table-row-current.js
app/styles/base/_typography.scss

Please test out this UI and make sure we want it. 
Closes #514.

Hovering or clicking a row adds an .is-selected style

---

app/components/comparison-area-selector.js
app/components/data-table.js
app/components/download-spreadsheet.js
app/components/layer-menu-item.js
app/components/map-search.js
app/components/map-utility-box.js
app/components/profile-footer.js
app/components/profile-header.js
app/components/tab-dropdown.js
app/controllers/index.js
app/controllers/profile.js
app/mixins/track-page.js
app/router.js
app/templates/components/map-utility-box.hbs
app/templates/components/profile-footer.hbs
app/templates/components/profile-header.hbs
app/templates/components/tab-dropdown.hbs
app/templates/profile.hbs
app/utils/track-event.js
config/environment.js
package-lock.json
package.json
yarn.lock

This PR adds google analytics!
Closes #327

327 analytics

---

app/templates/about.hbs

Closes #{588}
Added tutorial link in About Section for now, going to embed the video as soon as we have the permissions

Add tutorial link

---

app/styles/base/_typography.scss
app/templates/components/tab-dropdown.hbs

Make it so that hover dropdown occurs over entire menu tab

---

app/routes/index.js
app/templates/components/map-utility-box.hbs
app/templates/index.hbs

Closes #679 (with https://github.com/NYCPlanning/labs-layers-api/pull/102)

revise admin boundary colors with PFF crew

---

app/services/selection.js

This PR handles the block to puma transition using a spatial join, which was throwing an error in develop.
Closes #681

handle block -> puma transition

---

bin/develop

This adds a simple command for opening the full development environment for FF

696 Adds a develop executable to open relevant processes

---

app/templates/about.hbs

Add link to feedback form on About page 
Feedback Form:
https://docs.google.com/forms/d/e/1FAIpQLSe89pYgxjef01x3RYHw-fKqHcELjewRSU8u2ulAf-Jq1iTWEA/viewform

Add link to feedback form

---

app/adapters/row.js
app/components/data-table-row-change.js
app/components/data-table.js
app/components/download-spreadsheet.js
app/controllers/profile/census.js
app/controllers/profile/demographic.js
app/controllers/profile/economic.js
app/controllers/profile/housing.js
app/controllers/profile/social.js
app/mixins/downloadable.js
app/models/row.js
app/templates/components/data-table-row-change.hbs
app/templates/components/data-table-row-current.hbs
app/templates/components/data-table.hbs
app/templates/profile/census.hbs
app/templates/profile/demographic.hbs
app/templates/profile/economic.hbs
app/templates/profile/housing.hbs
app/templates/profile/social.hbs
tests/integration/components/data-table-row-change-test.js

backend changes https://github.com/NYCPlanning/labs-factfinder-api/pull/68

Updates ember data models & templates to work with the new backend

---

app/models/row.js
app/templates/components/data-table-column-group.hbs
tests/acceptance/click-view-profile-test.js

and clean up some trailing whitespaces I came across

Add missing previous.is_reliable that got lost in merge conflict resolution

---

app/models/row.js

Fix up the computed 'isSpecial' on row model

---

config/environment.js

point to production layers-api

---

app/table-config/housing/year-householder-moved-into-unit.js
config/environment.js

Update configuration in FE for new bottom-coding bin:
Implies removal of mvbf79 because this bin is included in the new bottom-coding variable “mvbf89"

Update year HH moved into unit

---

app/choropleth-config/index.js
app/templates/profile/economic.hbs
app/templates/profile/housing.hbs

https://github.com/NYCPlanning/labs-factfinder-api/issues/82#issuecomment-583478669
Changes the year to be correct.

Change year from 2016 to 2018

---

README.md
app/templates/application.hbs
app/templates/components/default-modal.hbs

- New Feature
- API change
AB#13385

13385 pff add a pop up message to the homepage

---

.circleci/config.yml
.github/workflows/main.yml
README.md
netlify.toml

Bumps the CircleCI build to use Node 12.18.4

Bump CI to node 12.18.4

---

mirage/config.js
mirage/scenarios/default.js
mirage/serializers/application.js
package.json
yarn.lock

This is preparation for frontend work on Data Explorer, Custom Map Study, etc.
Related to [AB#3170](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3170)

Install ember-mirage-cli

---

package.json
yarn.lock

Fixes [AB#3241](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3241)
This matches mapbox to the version used by Zap Search

3241 Upgrade Mapbox

---

app/controllers/explorer.js

- Fixes [AB#3164](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3164)
This is a bit of a silly PR

3164 Set up Explorer controller defaults

---

app/templates/components/orange-bar-data-explorer.hbs
app/templates/explorer.hbs

Thank you @dhochbaum-dcp
Simply inserting the toolbar base component created by @dhochbaum-dcp. Thx!
Fixes [AB#3207](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3207)

3207 Data Explorer toolbar base

---

app/components/explorer/topic-select-dropdown.js
app/templates/components/explorer/topic-select-dropdown.hbs

Displays number of selected topics in Topic Selection Dropdown button
Fixes [AB#3179](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3179)

Display number of topics selected

---

app/components/explorer/topic-select-dropdown.js
app/styles/modules/components/explorer/topic-select-dropdown.scss
app/styles/modules/components/ui/nestable-list-item.scss
app/templates/components/explorer/topic-select-dropdown.hbs

Implements toggling all topics
- Fixes [AB#3179](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3179)
- Fixes user story [AB#2124](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2124)

Toggle all topics, adjust styling

---

app/controllers/explorer.js
app/templates/explorer.hbs

Fixes [AB#3183](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3183)

3183 Render each selected topic as table

---

app/components/explorer/topic-select-dropdown.js
app/controllers/explorer.js
app/templates/explorer.hbs

Fixes [AB#3183](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3183)

3183 Handle switching between decennial and acs topic lists

---

app/components/explorer/source-select-dropdown.js
app/controllers/explorer.js
app/styles/app.scss
app/styles/modules/_m-orange-bar.scss
app/styles/modules/components/explorer/source-select-dropdown.scss
app/styles/modules/components/ui/nestable-list-item.scss
app/templates/components/explorer/source-select-dropdown.hbs
app/templates/components/orange-bar-data-explorer.hbs
app/templates/components/ui/nestable-list-item.hbs
app/templates/explorer.hbs

Sets up very basic Source selection dropdown. This allows us to switch between Topics list based on selected Source.
- Fixes [AB#3176](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3176)
- Fixes [AB#3177](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3177)
- Fixes [AB#3183](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3183)

3176 3177 3183 Switch Topics list based on selected Source

---

app/styles/app.scss
app/styles/modules/components/explorer/toolbar.scss
app/templates/components/orange-bar-data-explorer.hbs

Left-aligns the dropdowns in the Data Explorer toolbar. Also gives each dropdown a bit of margin between one another.

Format Data Explorer toolbar

---

app/components/explorer/modify-tables-menu.js
app/controllers/explorer.js
app/styles/app.scss
app/styles/modules/components/explorer/modify-tables-menu.scss
app/templates/components/explorer/modify-tables-menu.hbs
app/templates/components/orange-bar-data-explorer.hbs
app/templates/explorer.hbs

- Fixes [AB#3185](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3185)
- Partially fixes [AB#3186](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3186)
- Partially fixes [AB#3187](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3187)

3185 3186 3187 Modify Tables Dropdown basic UI. Connects showReliability and disaggregate states

---

app/controllers/explorer.js

Received clarification from client on what census topics to activate on defualt. Related to User Story [AB#2124](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2124)

Adjust census topic defaults

---

app/styles/modules/_m-orange-bar.scss
app/styles/modules/components/explorer/modify-tables-menu.scss
app/templates/components/explorer/modify-tables-menu.hbs
app/templates/components/explorer/source-select-dropdown.hbs
app/templates/components/explorer/topic-select-dropdown.hbs
app/templates/components/orange-bar-data-explorer.hbs

Left aligns the Topic selection, Source selection, and Modify Tables dropdown in Explorer toolbar.

Left align Explorer toolbar items

---

app/components/map-utility-box.js

Updated link from old profile page to new data explorer page.
- Implements [AB#3386](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3386)

3386 - See more data now llinks to data explorer.

---

app/components/comparison-area-selector.js
app/components/data-table-header-current.js
app/controllers/explorer.js
app/queries/geography-options.js
app/routes/explorer.js
app/styles/base/_typography.scss
app/templates/components/comparison-area-selector.hbs
app/templates/components/data-table-header-current.hbs
app/templates/components/data-table.hbs
app/templates/components/explorer/modify-tables-menu.hbs
app/templates/components/orange-bar-data-explorer.hbs
app/templates/explorer.hbs

- Fixes [AB#3198](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3198)

3198 compare to select

---

app/templates/components/explorer/modify-tables-menu.hbs
translations/explorer/modify-tables/en-us.yaml

Add tooltip text for Modify Tables dropdown controls
- Fixes [AB#3951](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3951)

3951 Add Explorer tooltip text

---

app/styles/modules/_m-search.scss

Updated z-index of loading menu.
- Fixes [AB#4016](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4016)

4016 - Make Search Loading menu visibile

---

app/styles/modules/_m-orange-bar.scss
app/templates/components/orange-bar-custom-map-study.hbs

Updates language of summary levels on the geography toolbar on the custom map study page, and makes necessary adjustments to styling based upon the change.
- Fixes [AB#4019](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4019)

4019 geography summary levels

---

config/icons.js

Added 'minus-square' to icons.js so that it loads.
- Fixes [AB#4075](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4075)

4075 Added minus-square to icons.js

---

app/styles/modules/components/explorer/download-data-dropdown.scss
app/templates/components/labs-ui/site-header.hbs

Removed the Planning Labs Beta thin orange bar from the top of the app.
- Fixes AB#4704

4074 Removed orange bar from header

---

app/templates/components/default-modal.hbs

Updates to welcome message.
- Implements [AB#4181](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4181)

4181 update current landing notice

---

app/controllers/explorer.js
app/router.js
app/routes/explorer.js
app/templates/application.hbs
app/templates/components/selection-details-text.hbs
config/environment.js

Parallel work to https://github.com/NYCPlanning/labs-factfinder-api/pull/110
Fixes [AB#3926](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3926)

3926 Accept geoid or selection ID as dynamic segment in Explorer route

---

app/templates/components/map-utility-box.hbs

Remove the summary statistics from the "Your Selection" box on the map page, because at the moment, we can't actually calculate them.
- Implements [AB#4211](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4211)

4211 Commented out summary statistics until they can be dynamically computed

---

app/queries/summary-levels.js
app/services/selection.js
app/sources/census-admin-boundaries.js

Updates sql queries for 2020 geos.
- Fixes [AB#4282](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4282)

4282 update sql queries with new 2020 geos

---

app/templates/components/default-modal.hbs

Per instructions from PopDiv team, this PR lets users know about upcoming changes to PFF.

Update modal text on front page

---

app/styles/base/_typography.scss

- Fixes [AB#4073](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4073)

4073 Active item in the top nav bar (custom map study, data explorer) is now underlined

---

.gitignore
netlify.toml

This is attempting to fix error happening in the netlify build
- Related to [AB#4711](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4711)

Updating netlify.toml

---

app/chart-config/acs/social/household-type.js

I went through the changes to the table config variables and made sure that corresponding variables in chart configs were updated accordingly. 
- Fixes [AB#4912](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4912)

4912 Update chart configs to match table configs

---

app/components/explorer/modify-tables-menu.js
app/templates/components/explorer/modify-tables-menu.hbs
app/templates/components/orange-bar-data-explorer.hbs

Hid reliability toggle unless ACS is selected
- Completes [AB#4909](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4909)

4909 Remove 'show Reliability' toggle for decennial

---

app/models/acs-row.js
app/models/decennial-row.js
app/templates/components/data-table-column-group.hbs
app/templates/components/data-table-row-change.hbs
app/templates/components/data-table-row-current.hbs
app/templates/components/data-table-row-previous.hbs

Merge must be synced with https://github.com/NYCPlanning/labs-factfinder-api/pull/182
Please see that backend PR for an explanation.
- Fixes [AB#4405](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4405)
This acs-row.js and decennial-row.js files are a mess to begin with. Very disorganized. Another PR we should organize it better.

4405 Rename significant to Reliable

---

app/models/acs-row.js
app/models/decennial-row.js
app/templates/components/data-table-column-group.hbs
app/templates/components/data-table-row-change.hbs
app/templates/components/data-table-row-current.hbs
app/templates/components/data-table-row-previous.hbs

4405 Rename reliable to isReliable

---

app/choropleth-config/index.js
app/components/map-toolbar.js
app/templates/components/map-toolbar.hbs

This PR to staging includes changes to re-implement the percent change choropleths, now with the correct logic to handle when the absolute count for those variables is below the minimum.

5382 Re-add racial percent change choropleths

---

app/utils/carto.js
config/environment.js
netlify.toml

Fixes [AB#7557](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/7557)

7557 Set Carto account via environment

---

app/topics-config/acs.js

Reorders ACS topics in Data Explorer.
- Fixes AB[#5019](https://dev.azure.com/NYCPlanning/ITD/_sprints/taskboard/Open%20Source%20Engineering/ITD/2022/Q3/Sprint%20O?workitem=5019)

5019 - Reorder ACS topics

---

app/topics-config/acs.js

updated the year on the Economic and Housing table headers in PFF
- Fixes [AB#9793](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/9793)

9793 updated tool tips per ado

---

app/table-config/acs/housing/gross-rent-as-a-percentage-of-household-income--grapi.js
app/table-config/acs/social/year-of-entry.js

Updates labels for ACS data points and IDs to match changes in new ACS data.
- Fixes AB[#9812](https://dev.azure.com/NYCPlanning/ITD/_sprints/taskboard/Open%20Source%20Engineering/ITD/2022/Q3/Sprint%20O?workitem=9812)

9812 – Update ACS variable IDs and labels

---

app/chart-config/acs/economic/index.js
app/chart-config/acs/economic/ratio-of-income-to-poverty-level.js
app/chart-config/acs/housing/gross-rent-grapi.js
app/chart-config/acs/housing/gross-rent.js
app/chart-config/acs/housing/index.js
app/components/acs-bar.js
app/styles/modules/_m-toolbar.scss
app/templates/components/explorer/modify-tables-menu.hbs
app/templates/explorer.hbs
app/topics-config/acs.js
app/utils/munge-bar-chart-data.js

- restore 3 bar charts for specific topics (ratio of income to poverty, gross rent, gross rent grapi )
- update to 2020 schema
- improve bar charts formatting
- move Show Charts toggle

Merge develop into staging

---

app/chart-config/acs/housing/gross-rent-grapi.js
app/controllers/explorer.js
app/topics-config/acs.js

Minor revisions per erica's comments in [AB#9888](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/9888)

10029 follow up revisions

---

app/components/map-utility-box.js
app/controllers/application.js
app/controllers/explorer.js
app/routes/explorer.js
app/templates/application.hbs

This PR updates the application to preserve the user's selections in the Data Explorer when navigating away and back.
- Fixes AB[#5532](https://dev.azure.com/NYCPlanning/ITD/_sprints/taskboard/Open%20Source%20Engineering/ITD/2022/Q3/Sprint%20P?workitem=5532)
Stores filter selections in Data Explorer in ```sessionStorage```. Added an action to the ```application.js``` controller to generate a URL with query params from values in ```sessionStorage``` (if any) when clicking on Data Explorer tab.

5532 – Maintain table selection when user returns to Data Explorer

---

app/styles/modules/_m-reveal-modal.scss
app/templates/components/default-modal.hbs
package.json

Updates modal message ahead of new ACS data release. Also fixes a bug where text was overlapping with the "X" in the modal and fixes the `engines` prop in package.json because this thing doesn't actually work with node 10 because of lint-staged.

New data modal change for release

---

app/templates/components/explorer/modify-tables-menu.hbs
app/templates/explorer.hbs
app/topics-config/acs.js

Fixes [AB#9888](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/9888) latest revision requests from Erica. PR from staging to release staging without not-yet-QA'd develop commits

9888 chart revisions.8.11.22

---

config/environment.js

- Fixes [AB#1234](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/1234)
- Related [AB#1235](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/1235)
- Reverses [AB#1222](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/1222)

Update to env to fix citynet issue.

---

app/components/population-pyramid.js
app/templates/components/population-pyramid.hbs

Fixes [AB#9971](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/9971)

9971 Add labels to pop pyramid

---

app/index.html
netlify.toml

Merging changes to add FullStory script up to staging

Merging develop to staging

---

app/templates/components/default-modal.hbs

Update copy of the modal on teh PFF homepage to reflect upcoming changes.
- Fixes [AB#11716](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/11716)

11716 updated copy of the default modal on the PFF homepage

---

app/components/data-table.js
app/templates/components/default-modal.hbs
app/templates/components/explorer/source-select-dropdown.hbs

This PR merges some changes up to staging for changing some copy and fixing a bug with the copy to clipboard functionality. See the original PRs against develop linked below to details

Merge copy changes and clipboard fix up to staging

---

app/sources-config/index.js
app/templates/components/data-table-header-change.hbs
app/topics-config/acs.js

12679 – Update references to year

---

app/templates/components/default-modal.hbs

Updates modal on Population FactFinder.
Resolves AB[#13158](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/13158)

Task/13158 – Update modal copy

---

config/environment.js

Merging small copy change in pop up to master for release.

Deploying small copy update to production

---

app/styles/app.scss
app/styles/modules/_m-spinner.scss
app/templates/components/acs-bar.hbs
app/templates/components/data-table-header-current.hbs
app/templates/components/data-table-header-previous.hbs
app/templates/components/horizontal-bar.hbs
app/templates/components/page-load-spinner.hbs
app/templates/explorer.hbs
app/templates/index.hbs
app/templates/loading.hbs

merging in a reversion of the lottie loading animation causing "blinking" in page load behavior and other unintended side effects.

merge dev onto staging for QA

---

app/styles/modules/_m-reveal-modal.scss
app/styles/modules/_m-site-header.scss
app/templates/application.hbs

Adds banner to top of the site with link to SendGrid sign up form.
Closes #1110

Add banner with link to sign up for user interviews

---

app/templates/application.hbs

Removing the sign up banner for user interviews.

Remove sign up banner

---

app/templates/application.hbs

Remove sign up banner from prod

Remove sign up banner from prod

---

netlify.toml

Adds a missing comma to netlify.toml that was making the file invalid and blocking deployments.

Add missing comma to netlify.toml

---

app/table-config/census/detailed-race-and-ethnicity.js

Updated pff variables for table
- Fixes #1164

issue 1164 updated pff variables for Detailed Race and Ethnicity table

---

app/choropleth-config/index.js

Updated the ID for target pop
- Fixes #1168

1168 updated id for pop 65 and over

---

app/table-config/census/detailed-race-and-ethnicity.js

fixed indentation
- Fixes #1170

Issue/1170 fix indentation detailed race & ethnicity table

---

app/templates/components/data-table-row-current.hbs
app/templates/components/data-table-row-previous.hbs

1171 updated copy to inform of suppressed data

---

app/templates/components/default-modal.hbs

Closes https://github.com/NYCPlanning/labs-factfinder/issues/1209

Update pop up text

---

app/templates/components/default-modal.hbs
app/topics-config/census.js

Merging upcoming data message for 2023 ACS to staging (see #1210) for original change.

Merging upcoming data message for 2023 ACS to master

---

app/templates/components/default-modal.hbs

Merging data update message up to staging

---

app/choropleth-config/index.js

Closes https://github.com/NYCPlanning/labs-factfinder/issues/1224

Remove last category for below poverty
