NYCPlanning/labs-factfinder

app/templates/components/site-header.hbs

This PR uses the `{{link-to}}` component for the `.site-name`. 
(It was just using `a href="#"`.)

use link-to for .site-name link

---

app/helpers/numeral-format.js
app/templates/report/demographic.hbs
tests/integration/helpers/numeral-format-test.js

Adds `numeral-format` helper, which now has a default numeral template of `0,0`, so it can be called without a second parameter, like {{numeral-format somevalue}}
Implements `numeral-format` on all of the values on the demographics page

Cw numeral format

---

app/controllers/report.js
app/templates/report.hbs

This PR improves the map on the report view:
- Removes the URL hash
- Makes the map static (non-interactive)
- Fits the map to the bounds of the selected area when the window is resized
Closes #37

make report map static, remove hash, fitbounds on resize

---

app/routes/report.js
app/services/selection.js
package.json

This PR implements closes #98, where carto SQL api calls were too long when many census blocks are selected.  Now the calls will use POST, which can have a larger payload.

Fix bug where very long SQL queries make the URL too long

---

app/styles/base/_typography.scss
app/styles/layouts/_l-default.scss

This PR: 
- Prevent floated elements appearing beside tables
- Auto-sizes the map (was just using mobile height for all screen sizes)

AC Table, Report Map tweaks

---

app/services/selection.js
app/sources/admin-boundaries.js
app/sources/census-geoms.js
package.json

This PR
- Temporarily fixes geometry type switching in selection (resets the selection where geometries cannot yet be exploded/imploded)
- Adds geolabels to all geometries
- Upgrades to ember-jane-maps v0.0.5 (deals with a "before" map layer error)

Cw reset ntapuma selections

---

app/styles/base/_typography.scss

This PR… 
- Forces tables to always be at least 100% width
- Removes the unused narrow cell class

Table Width Fix

---

app/styles/base/_typography.scss
app/templates/report/demographic.hbs

This PR simplifies the styles for table header cells. Since borders collapse, `th` can just have border on all sides, and there's no need for the classes on every single one.

Simplify th styles

---

app/styles/base/_typography.scss
app/styles/layouts/_l-default.scss

Nested grids were causing their parent cell to scroll horizontally. This PR addresses this issue by apply the `xy-cell-block()` mixin only to direct child cells of `.overflow-y-grid`, whereas is was previously/mistakenly applied to all cells in `.site-main`.

Fix horizontal scroll bug

---

app/styles/base/_typography.scss
app/templates/components/report-header.hbs
app/templates/report.hbs
app/templates/report/demographic.hbs

This PR moves the Current/Change report mode switcher UI into the report header, explicitly stating both modes in subheaders that function as radio buttons.

Mode switcher as subhead radios

---

app/controllers/index.js

This PR adds a workaround that will restore touch to select/deselect polygons on mobile devices.
A bug in `mapbox-gl-draw` causes it to hijack touch events even when the user is not actively drawing.  
The workaround is simply to add the draw control to the map only when the user clicks the draw button, and to remove it when they are done.  Once the bug is fixed we can revert to having the control on all the time.
Closes #202

hackfix for tap to select on mobile devices

---

app/components/map-utility-box.js
app/styles/base/_typography.scss
app/styles/layouts/_l-default.scss
app/styles/modules/_m-maps.scss
app/styles/modules/_m-search.scss
app/templates/components/map-utility-box.hbs
app/templates/index.hbs
tests/acceptance/select-geometries-test.js

In preparation for adding the "Advanced Options" to the selection route (@chriswhong is working on filters), I've rethought the layout. This PR… 
- moves search out of the selection overview box, as it's a separate action from making a selection
- combines the selection count and "view selection" button into one frickin' sweet button
- finds a better place for the "clear selection" button, moving it into the box
- restyles the "Advanced Options" button
- makes all of this work MUCH better on small screens 
- closes #219 
New layout (left) vs old layout (right)

Revised Selection Layout

---

app/components/map-utility-box.js
app/components/profile-header.js
app/controllers/index.js
app/index.html
app/templates/components/profile-header.hbs
app/templates/index.hbs

Adds a `lastreport` queryparam to `index` route which indicates the default tab when the user clicks "View report"
Clicking the "Edit Selection" from a report will load `index` with the respective `lastreport` param.
Closes #194

add lastreport query param

---

app/queries/intersection.js
app/queries/summary-levels.js

Fixes bug where using the draw tool on NTAs will select parks/cemeteries (non-nta spaces citywide).  Updates the query used to intersect with the drawn geometry to exclude the non-ntas.
Closes #133

fix parks draw selection bug

---

app/templates/profile/economic.hbs

Seemed to be an extra letter in the coding for the 2006-2010 occupation label. I think this may fix the problem of the data not appearing.

Fix occupation 06-10 data in table

---

app/templates/components/acs-table-row.hbs
app/templates/components/acs-table.hbs

This PR closed issue 122, 148, 149, 155, 186
#122 - associated data columns appears blank for estimates of 0
#148 - Remove "+" signs
#149 - Remove columns from change over time profiles
#155 - Data not available or null appears as blank
#186 -  2011-2015 data appears blank in change over time when 2006-2010 data is not available
#261 - User should not see percent change over time, when earlier time (Census 2000 or ACS 2006-2010) is blank or zero
Closes #122, closes #148, closes #149, closes #155, closes #186

addressed issue 122, 148, 149, 155, 186, 261

---

app/templates/profile/census.hbs

The tables in the Census profile were not being passed the `mode` var, so nothing happened when you switched modes. Closes #272.

pass mode to decennial tables

---

app/templates/components/acs-table-row.hbs

This PR adds logic to `acs-table-row` that checks for:
- estimates of 0 and grays out their associated columns
- CVs >= 20 and grays out their associated columns
Closes #29, some lingering issues from #29 are now in #157

add gray out rules for acs tables

---

app/components/acs-table.js
app/styles/base/_typography.scss
app/templates/components/acs-table-header.hbs
app/templates/components/acs-table.hbs

This PR fixes the issue where scrolling a table horz before making its header sticky causes a misalignment of the columns. The solution is to remove the scrolling table headers from the `.table-scroll` div, listen for the scroll, and and programmatically set the `.header-table`'s left-margin.

Scroll header-table programmatically

---

app/styles/layouts/_l-default.scss

This PR adds bottom padding to the profile. Its last table was flush against the bottom of the window, so you couldn't tell that you'd reached the end of the page. 
I've also nixed some old styles for the profile layout that we're no longer using.

Profile padding

---

app/styles/base/_typography.scss
app/templates/components/profile-header.hbs

This PR wraps the "compare to" UI in a conditional to only show for `mode: current`. 
Closes #310

nix compare UI in change mode

---

app/templates/components/profile-header.hbs

This PR removes the compare UI's checkbox in the profile header so that you cannot turn off the comparison. 
Closes #311

compare UI always on

---

app/components/data-table.js
app/styles/layouts/_l-default.scss
app/table-config/social/household-type.js
app/templates/components/data-table.hbs

This PR fixes a CSS regression that happened when `{{acs-table}}` was refactored and named `.data-table` (a class which already existed). I've changed what was previously `.acs-table` to `.body-table`, which is a better name since it works with the `.header-table` is used for sticky headers.

fix CSS regression from data-table refactor

---

app/routes/profile.js
app/services/selection.js
app/templates/components/profile-header.hbs

This PR updates the display labels for the list of selected geometries in the profile view
- Depends on new values coming back as `geoid` from calls to factfinder-api `/selection` endpoint which are already deployed
- Also fixes a bug where everything was labeled as "Tracts" when loading a Profile directly (when not coming from the selection view)
Closes #365

365 geography names

---

app/adapters/row.js
app/routes/profile/census.js

This PR adds some logic to the decennial route to make it listen for the comparator query param and adjust its queries accordingly.  
Adds comparison functionality to the decennial profile and closes #362

update decennial route to handle comparator param

---

app/queries/summary-levels.js
app/services/selection.js

This PR adds the ability to transition between all geography types.  
Prior to this, we were handling things via the `explode()` method, which is only helpful if we have good lookup columns in the tables (which we do for blocks -> tracts and tracts -> ntas.  
This was the initial implementation, but it would  not work with PUMAs at all, and if you skipped a level (tried to go from blocks to ntas for example) it would not work.
For those to/from pairs that `explode()` can't handle, this PR adds `explodeGeo()` which uses `ST_Intersects()` and lets postgis figure out what should be included in an explosion/implosion.
Caveats: With large numbers of geometries, the response can take a while, and we should explore concurrency to delay updating the UI.  When going from blocks to ntas with …

71 geom switching

---

app/mixins/downloadable.js

Adds conditional logic in route mixin to prevent app from applying aggregation logic
This PR prevents special aggregation methods when there is only one geography in the selection.
- Add conditional to ACS-relevant route mixin `downloadable` (should be renamed at some point) to prevent application of special aggregation methods to rows when # of geogs = 1. 
Related to #274, which was closed, but this detail was missed. Was mentioned in some issues by @EricaMaurer.
Closes #214.

Disallow single selection aggregation

---

app/queries/profile.js

This PR refactors the percent_m and comparison_percent_m fields in the ACS SQL query to better match what was provided by the customer and eliminate the square root of a negative error that was showing up after yesterday's fix
Related to #357

refactor percent MOE and Comparison percentMOE

---

app/queries/profile-simple.js
app/templates/components/data-table-row-current.hbs

This PR adds `cv` and `comparison_cv` to the SQL query for single geometry profiles
Closes #302

302 cv single

---

app/components/data-table-row-change.js

This PR prepends plus signs to change over time differences.  It does this by adding an `isChange` argument to the formatting functions in `data-table-row-change.js`
Closes #325

prepend plus signs to change variables

---

app/choropleth-config/index.js
app/components/comparison-area-selector.js
app/components/map-utility-box.js
app/templates/components/map-utility-box.hbs
app/templates/components/profile-header.hbs

This PR improves choropleth styling and configs, and adds groupings to the choropleth menu.
- Refactor choropleth configs to use a simpler breaks array and to use expressions instead of data-driven styling.  
- The expression allows for binning of values to make a choropleth, but does not interpolate values between breaks, so only the max value for a break needs to be specified
- Adds a `group` to each config, and uses `group-by` to add headings to the choropleth menu.
New headings need some design work, do not merge until @andycochran has added his touch.
Closes #291, Closes #303

refactor choropleths, add groups to menu

---

app/styles/base/_typography.scss
app/styles/layouts/_l-default.scss
app/styles/modules/_m-advanced-options.scss
app/templates/components/layer-menu-item.hbs
app/templates/components/map-utility-box.hbs

This PR adjusts the width of the `.map-utility-box`, gives the tooltips a color to indicate interaction, and prevents toggling layer items without content from adding space below themselves by removing the whitespace and hiding when `:empty`.

clean up layout of advanced options

---

app/adapters/row.js
app/templates/profile.hbs

This PR:
- updates the profile tabs so that the `comparator` query param is persisted (the selected comparison area will persist when switching tabs.
- adds `compare` query parameter to the `profile` API calls (restores comparison area functionality now that query logic has been moved to the backend)

423 persist comparison area

---

app/styles/base/_typography.scss
app/templates/components/data-table-row-change.hbs
app/templates/components/data-table-row-current.hbs
app/templates/profile/demographic.hbs
app/templates/profile/economic.hbs
app/templates/profile/housing.hbs
app/templates/profile/social.hbs
config/environment.js

This PR ensures that census profiles never include grayed out data
- cells classed `medium-gray` will now be classed `insignificant`
- all ACS profiles are wrapped in a div with class `shows-significance`
- a new CSS rule for `.shows-significance .insignficant` is added, changing the color to `$medium-gray`
Closes #315

ensure graying only occurs on acs profiles

---

app/controllers/index.js
app/layers/subdued-nta-labels.js
app/services/selection.js
app/templates/index.hbs

This PR hides the default neighborhood names included in the mapbox `composite` source, and adds a new custom layer called `subdued-nta-labels`.  
It also includes some handling to make sure that the subdued labels are not shown when selecting NTAs. (bold labels are shown for the NTAs when in NTA selection mode)
Closes #306

replace default basemap labels with nta labels

---

app/routes/profile.js

Bug: when you toggled reliability in Change Over Time mode, the `mode` was resetting to `current`. 
This PR scopes the `mode` query param to profile controller, which avoids resetting `mode` when toggling `charts` or `reliability` query param.

Checkbox query param bug fix

---

app/services/scroller.js

This PR fixes the scroll-to bug where scrolling to tables on a profile did not work after transitioning away from and back to a profile.
The `scroll-to` package included a computed property that returned a Jquery selection for the div to be scrolled.  I think that this computed property was not being recalculated after the route transition.  Although the div and id were the same the original one had been destroyed and a new one is created after the transition.
This adds the jQuery selection within `scrollVertical()`, so it's always new every time.  Will also update https://github.com/ragnarpeterson/ember-scroll-to/issues/39 with this information.
Closes #304

fix scroll-to bug

---

app/models/row.js
app/templates/components/data-table-row-change.hbs

This PR adds view logic for hiding percent changes when a property in the api table config are set to true.
Closes #448

Use rowconfig from server, not local; logic for hiding pct change

---

app/helpers/format-number.js
app/models/row.js
app/templates/components/data-table-row-change.hbs
tests/integration/helpers/format-number-test.js

This PR adds logic for treating nulls as blank when using the format-number helper. Other overriding logic still applies.
- New Feature
- API change
Closes #426

426 treat moe as 0 if

---

app/components/download-spreadsheet.js
app/models/row.js
app/templates/components/data-table-row-change.hbs
app/templates/components/data-table-row-current.hbs

This PR fixed the download CSV button by removing properties that are objects from the array that get's passed to `ember-cli-data-export`
Closes #516

516 fix download button

---

app/models/row.js
app/templates/components/data-table-row-change.hbs
app/templates/components/data-table-row-current.hbs

This PR adds logic to `data-table-row-current` and `data-table-row-change` to hide the right-most percentage point column based on nullness of other percentage columns.
-for current view, hides `difference_percent` and `difference_percent_m` if `data.percent and `data.previous_percent` are both null
-for change over time view, hides data `data.change_percentage_point` and `data.change_percentage_point_m` if `data.change_percentage_point` is null
Closes #522

522 hide percentage point

---

app/utils/radius-mode.js
package-lock.json
package.json
yarn.lock

This PR refactors the label calculator for the radius selection tool to only use 'large' units (miles and kilometers) with two digits of precision.
Closes #575

simplify measurement label, always show miles/km

---

app/components/tab-dropdown.js
app/services/scroller.js
app/templates/components/tab-dropdown.hbs
app/templates/profile.hbs

This PR… 
- Refactors the `tab-dropdown` component to minimize repeated code (there was a lot of repeated markup for every dropdown list item, which are now in an `{{each}}` template) 
- Reimplements @chriswhong's fix for the `{{scroll-to}}` addon not working on 2nd visits to `profile/` route (Closes #447 )
I'm not sure about why Chris's fix was removed. If you look at the [history of `scroller.js`](https://github.com/NYCPlanning/labs-nyc-factfinder/commits/develop/app/services/scroller.js), you can see that Chris's "fix scroll-to bug" was manually undone by @allthesignals. I can't tell from the subsequent commits if that was intentional. See also [ember-scroll-to issue](https://github.com/ragnarpeterson/ember-scroll-to/issues/39)

447 section scroll

---

app/components/tab-dropdown.js
app/templates/profile.hbs

The census tab's dropdown menu broke with the last change that refactored how the tab drodowns work. 
See there's just an empty div, all you get is the shadow: 
It was fixed by adding `censusItems` to the `dropdownItems` computed property, just like all the other dropdowns:

fix the census tab's section dropdown items

---

app/controllers/index.js
app/styles/app.scss
app/styles/modules/_m-dropzone.scss
app/templates/components/map-utility-box.hbs
app/templates/index.hbs
ember-cli-build.js

[WIP] Style Dropzone

---

app/controllers/index.js
app/styles/modules/_m-dropzone.scss
app/templates/index.hbs

This PR updates the styling for the uploaded shapefile overlay and allows points to be displayed.
- Detect geom type of the uploaded shapefile in `controllers/index` and assign a label (customVisualOverlayLines vs. customVisualOverlayPoints) that determines which styling should be applied to it in the template.
- Update`templates/index` to
- Add styling for points
- Update line styling to make line thicker and a little darker
- Render the uploaded lines and points on top of all other preset boundary overlays like CDs, NTAs, etc.
- Slightly change drag and drop instructions to make overlay functionality more explicit
Closes #622 . Closes #623

622 styling

---

app/components/acs-bar.js
app/templates/profile/demographic.hbs
app/templates/profile/economic.hbs
app/templates/profile/housing.hbs
app/templates/profile/social.hbs

This PR makes all d3 bar charts on the profiles use an X-axis scale that matches the max of the data included on the chart (inclusive of both the selected area and comparison area data + their respective margins of error)
- Calculate xMax in the acs-bar component.
- Remove xMax=1 that has been set in each of the templates where the charts are being inserted.
Closes #617

617 chart ranges

---

app/routes/index.js
app/services/selection.js

This PR… 
- Separates the layer groups for selecting geometries from the layer groups in advanced options—which fixes a bug where changing the selection geom toggled the layers in adv options and vice-versa. Closes #651.
- Makes the tract styling more prominent while selecting by block. ~Closes #48~ (wrong repo). Closes https://github.com/NYCPlanning/labs-factfinder-api/issues/48. 
This PR relies on https://github.com/NYCPlanning/labs-layers-api/commit/206a0b8d10081ced8b50400726c4e04423576272. So, when this is merged into `master`, the layers API `develop` needs to also be promoted to `master`

Layer Groups Refactor

---

app/components/labs-map.js

added `highlightedFeatureLayer` from ember-labs-composer to `labs-map.js`, edited line color to grey
Closes #664

Change geom highlight color to grey

---

app/components/acs-bar.js

using `.tickSizeOuter([0]);`, reduce the final tick size to 0 for d3 charts
Closes #660

Reduce outer tick size to 0

---

app/controllers/index.js
app/routes/index.js
app/services/selection.js
app/templates/index.hbs

This PR addresses the bug where census tracts are showing when navigating back to the index route from a profile.
- All of the `factinder--` prefixed census geometry layergroups are now set to `visible:false` in the route.
- `handleSummaryLevelToggle()` is triggered at the end of `handleMapLoad()` (after the map loads, make the appropriate census geometry layer visible)
- The subdued NTA labels layer is now added in javascript in `handleMapLoad()`, as it needs to exist on the map before we turn on the census geometries. 
Closes #665

665 geom layer bug

---

app/services/selection.js

Adds handling for the `nta -> tract` geo explosion, which was not covered before for some reason.
Closes #667

add handling for nta -> block explodeGeo

---

app/components/download-spreadsheet.js
app/models/row.js
app/templates/components/map-utility-box.hbs
app/templates/components/profile-header.hbs
tests/acceptance/user-can-toggle-between-geometries-test.js

This PR updates the CSV download:
**- For ACS profiles**
-removes 2006-2010 rows
-displays reliability and significant columns as TRUE/FALSE
-reorders and removes columns based on attached file in issue #567 
-`change` and `difference` columns changed to `reliable` rather than `significant`
**- For Census**
-removes 2000 rows
-reorders and removes columns based on attached file in issue #567 
Closes #567

567 CSV download

---

app/components/acs-bar.js

This PR does two things:
- Adds a function `limitMax` which checks for whether a maximum x value is greater than `1`, and if so, sets the maximum to `1`
- Adds a new condition to `widthFunctionMOE`: if the percentage bar + the MOE bar extend past 100% percent on the x axis. If so, modify the MOE bar width to only extend to the remaining space between the end of the percentage bar and 100%. 
closes #685

685 MOE bar fix

---

app/choropleth-config/index.js

Update map breaks for four variables: `popu181` estimates, `ea_bchdh` estimates, `pbwpv_p` percentages, and `mdgr` estimates
Closes #659

659: update map breaks

---

app/router.js
config/environment.js

Page views and events are registering in the console for Google Analytics, so this should work in the online profile as well.

603: add track-page mixin to router to track pages for analytics

---

app/queries/summary-levels.js
app/sources/census-admin-boundaries.js

This PR updates Carto queries to query from aliased views of the latest dataset version. This reduces data maintenance overhead (now we only need to redefine the view when we get a new data version instead of find/replacing the table name throughout the code base) and makes this app match data view references used in all our other apps.
Related to https://github.com/NYCPlanning/labs-layers-api/pull/124

use-aliased-data

---

app/choropleth-config/index.js

Updates the binning for popu181 in the choropleth map.
See https://github.com/NYCPlanning/labs-factfinder-api/issues/82
Relevant bullet:
> Thematic Maps: Change categories for 'Under 18 Years':
> 20,000 or more
> 15,000 to 19,999
> 10,000 to 14,999
> 8,000 to 9,999
> Under 8,000
In this PR, I change the "stops" property, which is a MapboxGL Style Specification feature. The request from Erica was to change how things were binned (i think this comes from the census bureau).

Change the bins for popu181 choropleth map

---

package.json
yarn.lock

Fresh installs of dependencies were failing, throwing “Invalid or unexpected token” related to icons in labs-ui. This PR upgrades labs-ui and seems to resolve the issue.

Bump version of labs-ui

---

app/templates/application.hbs

This PR simply comments out the `{{default-modal}}` component in the application template. (Left it in there for future use.)

Disable the default modal

---

app/router.js
app/routes/explorer.js
app/routes/profile.js
app/templates/explorer.hbs

Fixes AB#3164
PR introduces basic route (/explorer) js and templates for the Data Explorer.
Although it is similar to the previous /profile route, since the user stories/wireframe brand this feature as "Data Explorer", I thought it would be good to migrate the code to reflect this as well.
Thinking we can keep the /profile route code available while we build out, and slowly extract and migrate necessary code over to the /explorer route.

3164 Set up stub data explorer route

---

app/controllers/application.js
app/styles/base/_typography.scss
app/templates/application.hbs

Fixes AB#3166 
Update header to match wireframe:
Links are orange when user is on respective route

3166 Update app header links, styling

---

app/templates/application.hbs
app/templates/components/data-table-row-change.hbs
app/templates/components/default-modal.hbs
app/templates/components/horizontal-bar.hbs
app/templates/components/labs-map.hbs
app/templates/components/labs-ui/icon-tooltip.hbs
app/templates/components/labs-ui/layer-group-toggle.hbs
app/templates/components/labs-ui/site-header.hbs
app/templates/components/layer-group.hbs
app/templates/components/layer-menu-item.hbs
app/templates/components/lookup-layer-group.hbs
app/templates/components/map-search.hbs
app/templates/components/map-utility-box.hbs
app/templates/components/orange-bar-custom-map-study.hbs
app/templates/components/reveal-modal.hbs
app/templates/components/switch-toggle.hbs
app/templates/components/tooltip-renderer.hbs
app/templates/index.hbs

Changes implicit references to component class properties to `this.` prefixed refs.
Ran this coded and it affects only components: https://github.com/ember-codemods/ember-no-implicit-this-codemod

Apply codemod: No Implicit “This”

---

app/components/explorer/topic-select-dropdown.js
app/components/ui/nestable-list-item.js
app/controllers/explorer.js
app/styles/app.scss
app/styles/modules/components/explorer/topic-select-dropdown.scss
app/styles/modules/components/ui/nestable-list-item.scss
app/templates/components/explorer/topic-select-dropdown.hbs
app/templates/components/orange-bar-data-explorer.hbs
app/templates/components/ui/nestable-list-item.hbs
app/templates/explorer.hbs
config/environment.js

This PR sets up the styled topic selection dropdown UI. Upcoming PRs will handle modifying topic selection state using actions.
Fixes [AB#3173](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3173)
PR sets up new components:
- topic-select-dropdown  -- the component representing the dropdown
- nestable-list-item -- component representing each expandable/collapsible topic in the dropdown. It can be recursively nested, and is data driven. 
PR sets up the new `app/components/ui` folder to hold general (non-labs ui) UI components, not specific to any page in Factfinder. 
PR also sets up new hierarchy in the `styles/modules/` folder.:
- `styles/modules/components` -- holds scss files associted to components. Within this folder, the hierarchy should match …

3173 Basic Topic Select Dropdown UI

---

app/components/explorer/topic-select-dropdown.js
app/components/ui/nestable-list-item.js
app/controllers/explorer.js
app/templates/components/explorer/topic-select-dropdown.hbs
app/templates/components/orange-bar-data-explorer.hbs
app/templates/components/ui/nestable-list-item.hbs
app/templates/explorer.hbs

This PR introduces actions to update a state array representing selected topics. It ties checkboxes in the topic selection dropdown to the new actions. The actions will make sure that toggling a parent topic results in toggling child topics.
- Fixes [AB#3179](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3179)

3173 Modify selected topic state

---

app/adapters/row.js
app/controllers/explorer.js
app/routes/explorer.js
app/templates/explorer.hbs
config/environment.js
mirage/config.js

- Combines /profile and /<topic> (/demographic, /sex-and-age, etc) routes into one route: /explorer
- /explorer model is combination of  both /profile and /topic models 
- Moves Downloadable Mixin procedures/transformations into explorer route
API ARCHITECTURE CHANGE ASSUMPTION (debatable):
- remove /profie/id/**/<topic>** subroute.  Load all topics at once in exploer.
- pros: faster ui
- cons: tiny bit slower to load explorer page
Fixes [AB#3183](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3183)
Other:
- re-enables Mirage in development mode

3183 Merge Profile n Topic route into Explorer route

---

app/formats.js
app/routes/index.js
app/templates/components/explorer/modify-tables-menu.hbs
config/ember-intl.js
package.json
translations/explorer/modify-tables/en-us.yaml
yarn.lock

Introduces a library, ember-intl, to help centralize text snippets that will be used throughout the application. Its first use is to hold text snippets for the Modify Tables dropdown tooltips. 
- Fixes [AB#3188](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3188)
The central location for all the text snippets is in the `translations` folder. 
I turned on `ember-intl`'s "wrapTranslationsWithNamespace" option, so when you reference text snippets, you have to namespace them using their folder path within the `translations` folder. For example, to reference the text in  `translations/explorer/modify-tables/en-us.js` from a handlebars template, write `{{t 'explorer.modify-tables.<key>}}`

3188 Ember Intl & "Modify Tables" dropdown tooltips

---

app/components/orange-bar-custom-map-study.js
app/styles/app.scss
app/styles/layouts/_l-default.scss
app/styles/modules/_m-orange-bar.scss
app/styles/modules/components/custom-map-study/toolbar.scss
app/styles/modules/components/explorer/source-select-dropdown.scss
app/styles/modules/components/explorer/toolbar.scss
app/styles/modules/components/explorer/topic-select-dropdown.scss
app/templates/components/orange-bar-custom-map-study.hbs
app/templates/components/orange-bar.hbs

Reworks the orange bar to use the Foundation XY Grid system to organize its layout at the top level, instead of the Foundation Menu component styles. Within each XY Grid cell, the Custom Map Study orange toolbar still uses the Foundation Menu component styles and system of `<ul>` and `<li>`.
However, using the XY Grid at the top level allows us to space items apart across the entire width of the toolbar in a more predictable way. E.g. one set of buttons on the left, another set on the right.  It also sets us up for success when we do mobile work in the future. 
This PR also removes unnecessary, over-complex code.
- Fixes [AB#3595](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3595)
- The `orange-bar` base component now is a `<div>` instead of a …

3595 fix orange bar arch

---

app/styles/modules/components/explorer/modify-tables-menu.scss
app/styles/modules/components/explorer/source-select-dropdown.scss
app/styles/modules/components/explorer/topic-select-dropdown.scss
app/templates/components/orange-bar-data-explorer.hbs

Small adjustment of Explorer toolbar buttons to match wireframes. Now that #829  is merged, this was a silky smooth fix!
Also tweak dropdown border radius.

Adjust position of Explorer toolbar buttons.

---

app/components/explorer/source-select-dropdown.js
app/controllers/explorer.js
app/styles/modules/components/explorer/modify-tables-menu.scss
app/styles/modules/components/explorer/source-select-dropdown.scss
app/styles/modules/components/explorer/topic-select-dropdown.scss
app/styles/modules/components/ui/nestable-list-item.scss
app/templates/components/explorer/source-select-dropdown.hbs
app/templates/components/orange-bar-data-explorer.hbs
app/templates/explorer.hbs

Allows the user to select "Change over Time" Census and ACS source options in the Source selection dropdown. 
Includes miscellaneous styling adjustments. 
- Fixes [AB#2126](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2126)
Reworks the Source objects to have more granular attributes, including a "changeOverTime" attribute which indicates if it represents a "Change over Time" source. 
Another new attribute on the source object is "type", which indicates if it is a Census or ACS source. Code should now reference this attribute to determine whether the current selected source is Census or ACS.

2126 Change over Time selection

---

app/templates/components/orange-bar-custom-map-study.hbs

Small PR to fix the More Options button jumping down on small-medium sized screens. The PR sets `align-spaced` on the parent grid-x container and removes a filler cell. Result is nicer spacing of buttons across the Custom Map Study toolbar.

Set align-spaced on CMS toolbar

---

app/templates/components/data-table-header-change.hbs
app/templates/components/data-table-row-change.hbs
app/templates/explorer.hbs
config/environment.js

Adds up and down arrows to the Change over Time columns. Up arrows correspond to positive values, and down to negative values.  
Had trouble adding an extra columns for the arrows and getting them to align properly with the headers, so adding them to inside the value cells for now. 
Fixes [AB#2126](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2126)
I was able to align subheaders to headers properly with `colspan` on `<th>`, but couldn't  seem  enough to line up cells to the subheaders, despite quadruple counting the cells to match the subheader column count.

2126 Show Change over Time arrows

---

app/chart-config/demographic/index.js
app/controllers/explorer.js
app/templates/explorer.hbs

Displays charts for some ACS demographic topics. We still need to go through all the topics and connect them to any (previously) available chart configurations. Not sure if it's a good use of time though if the incoming data has different variables or chart availability. 
Still need to implement chart toggle.
- Fixes [AB#3196](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3196)

3196 Add basic example charts for some ACS

---

app/controllers/explorer.js
app/styles/modules/components/explorer/modify-tables-menu.scss
app/templates/explorer.hbs

Adds a switch to toggle the Explorer charts. 
Adds the "Your Data" header above the chart toggle.
Erica specified toggle shouldn't got into Modify Tables dropdown.
It does look a little awkward sitting in the blank space above the tables -- maybe later can explorer putting it in the toolbar. 
Fixes [AB#3196](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3196)

3196 Add Show Charts toggle, Your Data header

---

app/chart-config/economic/index.js
app/chart-config/housing/index.js
app/chart-config/social/index.js
app/templates/explorer.hbs
app/topics-config/acs.js

Fills out the rest of the ACS > Social topic options. Attaches them to available charts configurations. 
Introduces new chart-config index exports for each topic folder under `chart-config/` .
The `topic-config` files will import from these chart-config index exports.
Each Topic configuration object (in `topic-config` files) will now have a `charts` attribute. It is an array of `chart` objects, which  point to the chart configuration objects and provides a chart label. 
Fixes [AB#3196](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3196)

3196 Fill out Social topics, charts

---

app/chart-config/demographic/index.js
app/chart-config/economic/index.js
app/chart-config/housing/index.js
app/chart-config/social/index.js
app/topics-config/acs.js

Fill out Economic, Housing ACS topics and charts. Simplifies and normalizes some topic IDs and imported variable names 
Fixes [AB#3196](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3196)

3196 Fill out Economic, Housing ACS topics and charts

---

app/components/explorer/topic-select-dropdown.js
app/templates/components/explorer/topic-select-dropdown.hbs
app/templates/components/ui/nestable-list-item.hbs
app/templates/explorer.hbs
app/topics-config/acs.js
app/topics-config/census.js
config/environment.js

Implements an "indeterminate" state for topics in the Topic Select Dropdown. The pattern and UI follows the Google Material UI spec. If some but not all subtopics are selected, then the parent topic will show a bar inside a box to show partial, i.e. "indeterminate", selection. If a user clicks on the indeterminate parent topic, all child subtopics will be unselected.
- Fixes [AB#3671](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3671)

3671 indeterminate state topic select

---

config/environment.js

Use Mirage for now.
Eventually it will connect to the new Heroku develop instance that will evenetually point to factfinder-staging DB
with WIP data.
Fixes [AB#3914](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3914)

3914 Configure new develop (cleanup branch) site

---

app/controllers/explorer.js
app/templates/components/explorer/modify-tables-menu.hbs
app/templates/components/orange-bar-data-explorer.hbs
app/templates/explorer.hbs

Set up query parameters for toggling reliability data and toggling charts. Connects them to the respective UI toggles.
- Fixes [AB#3925](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3925)
- Move from Ember `<Input />` to native HTML `<input />` to remove two-way binding on inputs.
- Passes action down from explorer controller to inputs. On input click, the action will trigger url parameter update. Url parameter state flows down to controller property state.

3925 Sets up queryParams for showReliability and showCharts

---

app/controllers/explorer.js
app/services/selection.js
app/templates/components/select-geography-list.hbs
app/templates/components/selection-details-text.hbs
app/templates/explorer.hbs

- Reworks old geography summary components and integrates them with new state flow.
Instead of depending on old selection service, they compute off of the upstream selection model.
The relevant selection service computed properties have been moved to the explorer controller. 
- Reworks HTML formatting
TODO: Need to verify that the selection model `type` property is reliable for different geographies.
Current static data provides the `ntas` value for `type`. It should also provide other values like `tracts`, `blocks`, `pumas` etc. 
- Fixes [AB#2862](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2862)

2862 Set up Explorer geography summary

---

app/components/explorer/source-select-dropdown.js
app/controllers/explorer.js
app/templates/components/explorer/source-select-dropdown.hbs
app/templates/components/orange-bar-data-explorer.hbs
app/templates/explorer.hbs

Source state is now held by a URL  query parameter. Allows users to copy URL to preserve selected state. 
- Fixes [AB#3961](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3961)
- Controller and Component actions no longer modify the `sources` array directly. Instead, they update the `source` URL query parameter.
- The `source` query param value should be one of the `id` property values seen in `sources-config/index.js` 
- Actions shall now update the source QueryParam by "Setting" the `source` property. There is a new setter for the `source` property which triggers the queryParam update.
- The `source` URL parameter actually maps to a `sourceId` string property, since the Explorer controller `source` represents a full Source POJO.  
- The sources …

3961 QueryParam for selected source

---

app/styles/modules/components/explorer/download-data-dropdown.scss
app/templates/components/orange-bar-data-explorer.hbs

- Prevents data download button from jumping to next line (when window was still medium - large)
- Centers the menu triangle relative to the button. 
Now:
Previously:

Fix Data Download menu positioning

---

app/components/explorer/download-data-dropdown.js
app/templates/components/explorer/download-data-dropdown.hbs

This fixes the indicator of the number of selected topics, and the list of selected topics shown in the download drop-down menu.
- Fixes [AB#4087](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4087)
- Fixes [AB#4088](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4088)

4087 4088 dynamic selected topic in download dropdown

---

app/controllers/index.js
app/layer-groups/boroughs.js
app/layer-groups/cdtas.js
app/layer-groups/census-blocks.js
app/layer-groups/cities.js
app/layer-groups/districts.js
app/layer-groups/index.js
app/queries/summary-levels.js
app/routes/index.js
app/services/selection.js
app/sources/census-admin-boundaries.js
app/styles/modules/_m-orange-bar.scss
app/styles/modules/_m-search.scss
app/templates/components/map-search.hbs
app/templates/components/orange-bar-custom-map-study.hbs
app/templates/components/selection-details-text.hbs

This adds four new summary levels for users to select - CDTA, Community District, Borough, and New York City.
It also updates the search functionality to return results on the correct levels.
- Completes (with changes to layers api and factfinder api) [AB#3142](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3142) and [AB#3148](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3148)

3142, 3148 - add new summary levels and rework search

---

app/components/explorer/download-data-dropdown.js
app/components/explorer/modify-tables-menu.js
app/components/explorer/source-select-dropdown.js
app/components/explorer/topic-select-dropdown.js
app/templates/components/explorer/download-data-dropdown.hbs
app/templates/components/explorer/modify-tables-menu.hbs
app/templates/components/explorer/source-select-dropdown.hbs
app/templates/components/explorer/topic-select-dropdown.hbs
package.json
yarn.lock

Now, when clicking outside of an open menu on the data explorer page, the menu will automatically close.  Commit message is incorrect, it is the data explorer page, not the custom map study page. 
- Fixes [AB#4150](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4150)
Uses an ember addon called ember-click-outside.  Documentation: https://github.com/zeppelin/ember-click-outside

4150 Menus on data explorer page now close when clicking outside of menu

---

app/components/map-utility-box.js
app/routes/index.js
app/services/selection.js

This PR
1.  tweaks the signature of the POST request to the selection POST endpoint. Necessary to integrate with changes in https://github.com/NYCPlanning/labs-factfinder-api/pull/124
2. Determines if the user selected one or multiple geographies. If...
a. Multiple geographies selected:  Acquires selecttion id from the selection POST endpoint. Then passes the newly acquired selection ID (hash from the Selection table) to the Explorer route.
b. Single geography selected: Passes the single geoid directly to the Explorer route 
3. Makes sure the NTA geography layer is pointing to the `factfinder--census-tracts-2020` Layers API layer instead of ``factfinder--census-tracts`. The former contains the actual new, ad hoc 2020 geography. 
Fixes …

4103 Pass selected geo to Explorer

---

app/styles/base/_typography.scss

Unreliable data now appears as grey instead of black
- Closes [AB#4221](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4221)
Quick CSS fix.  The "shows-significance" class is no longer being used.  The "insignificant" class is not being used anywhere but the unreliable data, so we could safely remove the "shows-significance" portion of the style.

4221 - MOE - Greyed out data deemed insignificant

---

app/routes/index.js
app/services/selection.js

This fixes the issue of the selected area expanding when returning to the map page from the data explorer.  It also fixes the console errors on the custom map study page.
- Fixes [AB#4652](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4652)
The console errors were due to the removed row being a duplicate (it still exists in row 56).
The geometries were altered because handleSummaryLevelToggle fires when the map page loads, which when a summary level was already selected, was expanding the area.  The fix simply exits the function without doing anything if it is triggered to toggle to the same level it already was.

4652 - Returning to Custom Map Study from Explorer alters selected geometry

---

app/services/selection.js

Initial fix was preventing the Census Tracts from appearing when first loading the site.  This fix moves the check to prevent toggling to the same level until later in the function, so that the layer group will render on initial page load.
- Fixes [AB#4652](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4652)

4652 - Geo Selection Toggle (FIX)

---

app/adapters/row.js
app/components/map-utility-box.js
app/controllers/explorer.js
app/router.js
app/routes/explorer.js
app/templates/application.hbs
app/utils/fetch-explorer-model.js

API was recently changed so that  Selection and Profile endpoints to have :geotype and :geoid dynamic segments, replacing the previous Factfinder ID. See updated README in Factfinder API for new API.
This PR updates fetch requests on the frontend to integrate with the new API. 
Pairs with https://github.com/NYCPlanning/labs-factfinder-api/pull/131
Depends on/merge after https://github.com/NYCPlanning/labs-factfinder-api/pull/130
- Fixes [AB#4281](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4281)

4281 Dynamic segments for geotype and geoid

---

README.md
config/environment.js
package.json

You can use 'yarn run local-api' to start a development server which uses labs-factfinder-api and labs-layers-api also running on localhost.

Environment variables for using local APIs

---

app/adapters/acs-row.js
app/adapters/decennial-row.js
app/templates/application.hbs
app/utils/fetch-explorer-model.js

Previously the Explorer URLs to access citywide/NYC data involved `boroughs` as the geotype and `NYC` as the geoid. 
This PR changes the endpoints so that NYC geoid(s) pair with the `cities` geotype, as it should.
E.g. old Explorer URL:
`/explorer/boroughs/NYC`
New:
`/explorer/cities/NYC`
Also the explorer URL now accepts different forms of the NYC geoid, e.g. 'New York City'.
This is also necessary because the Carto layer for NYC uses the geoid 'New York City'.
Additionally, geoids are now case-insensitive.
Pairs with https://github.com/NYCPlanning/labs-factfinder-api/pull/135
- Fixes [AB#4843](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4843)

4843  Accept `cities` geotype and various NYC geoids

---

app/layer-groups/neighborhood-tabulation-areas-selection.js
app/layer-groups/nyc-pumas-selection.js
app/layers/draw-styles.js
app/styles/base/_typography.scss
app/styles/layouts/_l-default.scss
app/styles/modules/_m-colors.scss
app/styles/modules/_m-dropzone.scss
app/styles/modules/_m-labs-beta-notice.scss
app/styles/modules/_m-layer-groups-menu.scss
app/styles/modules/_m-orange-bar.scss
app/styles/modules/_m-site-header.scss
app/styles/modules/components/explorer/download-data-dropdown.scss
app/templates/components/data-table-header-change.hbs
app/templates/components/data-table-header-current.hbs
app/templates/components/data-table-header-previous.hbs
app/templates/components/explorer/source-select-dropdown.hbs
app/templates/components/explorer/topic-select-dropdown.hbs
app/templates/components/map-utility-box.hbs
app/templates/components/ui/nestable-list-item.hbs

Replaced all instances of dcp-orange with a11y-orange.
Changed light gray and gray text to dark gray.
The site now passes contrast checks.
- Completes [AB#4866](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4866)
- Completes user story [AB#4724](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4724)

Replaced all instances of dcp-orange with a11y-orange.

---

app/styles/modules/components/explorer/topic-select-dropdown.scss

Users could open multiple tabs in the dropdown, making it larger than the screen height and rendering them unable to view portions of the menu.  The menu now has a maximum height, after which a scrollbar will appear.
- Fixes [AB#4112](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4112)
It's 2 lines of CSS copied from the download-data-dropdown-body class.

4112 Key interface elements are inaccessible within Topics dropdown

---

app/styles/modules/components/explorer/topic-select-dropdown.scss

Updated drop-down height to account for small window sizes.
- Fixes [AB#4112](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4112)

4112 Key interface elements are inaccessible within Topics dropdown (FIX)

---

app/components/explorer/source-select-dropdown.js
app/templates/components/explorer/source-select-dropdown.hbs
app/templates/components/orange-bar-data-explorer.hbs
app/templates/explorer.hbs

Updated sources drop-down to hide ACS options if the geotype is districts or blocks.
- Completes [AB#4182](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4182)
This pulls the geoType from this.model.selection.type (which always shows the geoType) rather than this.model.geotype (which returns 'selection' if more than one geo is selected).

4182 On Explorer, disable ACS source for community districts and blocks

---

app/models/decennial-row.js

The numbers on Decennial tables were showing up as gray because the reliability variables like `is_reliable` and `percent_significant` defaulted to null, or false. The API will calculate these reliability variables for ACS, but it isn't applicable for decennial and those variables remain null. Thus we set the default to `true` so those values are not grayed out on the frontend. 
- Fixes [AB#4810](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4810)

4810 Default reliability Survey attributes to True for decennial

---

app/templates/explorer.hbs

At some screen sizes, there were instances where the last row of data on the page was hidden.  I added an <hr> tag to the end of the page to ensure everything shows.
- Fixes [AB#5035](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/5035)

5035 Last row of data is cut off at end of page

---

app/chart-config/census/race-group.js
app/components/acs-bar.js
app/components/data-table-row-change.js
app/sources-config/index.js
app/templates/components/acs-bar.hbs
app/templates/components/data-table-header-change.hbs
app/templates/explorer.hbs

This PR Fixes three bugs. One is just updating the text in the survey selection dropdown and some tooltips to reflect the new census years. Another was an issue where zeros were showing for nonexistent comparison variables in the data explorer instead of the user friendly text that should appear. The last is improving the bar chart component to work with decennial data.
- Fixes [AB#5065](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/5065)
- Fixes [AB#5023](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/5023)
- Fixes [AB#5117](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/5117)

updating source list copy, fixing issue with missing previous compare, fixing decennial bar chart

---

app/models/acs-row.js
app/models/decennial-row.js
app/templates/components/data-table-column-group.hbs
app/templates/components/data-table-row-current.hbs

This PR renames some row properties to match the new ones coming back from the API. This fixes an issue where the difference fields weren't being correctly grayed-out based on reliability
- Fixes [AB#5033](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/5033)

Fixing reliability display bug

---

app/services/selection.js
app/templates/index.hbs

Previously, user selections of large geographies like CDTAs and Boundaries would get cut off at tile boundaries. 
It turns out this is known behavior with the mapbox-gl issue. When accessing the geometry through the click event, that geometry data is clipped at the tile edges. 
The temporary workaround here is to grab the geoid of the clicked geography, and make a second request to Carto for the entire geography. 
I limited this workaround to just CDTAs, Boroughs, Districts and Cities since those are the only ones exhibiting the issue. Also, for the other geos there is an attribute mismatch between the summary level table queries and the layer sources (from the Layers API), which causes some errors.
- Fixes [AB#4542](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_w …

4542 Fix for selections being cutoff at tile boundaries

---

app/models/acs-row.js
app/models/decennial-row.js

This PR fixes a bug where previous comparison MOEs were showing up as 0 because a variable was incorrectly named.
- Fixes [AB#5189](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/5189)

Fixing moe variable naming bug

---

app/models/acs-row.js
app/models/decennial-row.js

This PR fixes some more bugs related to property renaming. Due to some branches that hadn't been tested in aggregate before deploying (my bad) data in the explorer page wasn't showing up.

Fixing moe var naming

---

app/models/acs-row.js
app/models/decennial-row.js

@dhochbaum-dcp  also thinks these are not used

Clean out unused vars

---

app/choropleth-config/index.js
app/components/map-toolbar.js
app/templates/components/map-toolbar.hbs

This PR creates a production deployment that re-implements the percent change choropleths, now with the correct logic for graying-out ntas where the corresponding absolute count variable is below a minimum.

5382 Re-add racial percent change choropleths

---

app/sources-config/index.js
app/templates/components/data-table-header-change.hbs
app/templates/explorer.hbs
translations/explorer/modify-tables/en-us.yaml

Updates references to ACS data from 2015-2019 to 2016-2020. Updates ACS reliability warning copy.
Updated warning and tables:
Updated dropdown:
- Resolves AB[#9787](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/9787)
- Resolves AB[#9788](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/9788)

9787-9788 – Text updates

---

app/controllers/index.js
app/styles/modules/_m-reveal-modal.scss
app/templates/application.hbs
app/templates/components/default-modal.hbs
app/templates/index.hbs

This PR updates `default-modal` to display a message informing users of incoming ACS dataset changes. The modal conditionally renders either this message or the existing mobile warning depending on the user's device.
- Fixes AB[#9900](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/9900)

9900 – Pre-release ACS data modal 

---

app/templates/components/data-table-header-change.hbs
app/templates/components/data-table-header-current.hbs
app/templates/components/data-table-header-previous.hbs

Wrapped the significance tooltips in blocks to hide all on decennial pages/tables
- Fixes [AB#9908](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/9908)

9908 hide all significance arrows on decennial pages/tables

---

app/components/acs-bar.js
app/templates/explorer.hbs
app/utils/munge-bar-chart-data.js

This is a first pass of restoring all ACS bar charts. Previously 2020 bar charts appeared without issue, but 2010 bar charts yielded errors and comparison area percentage did not appear in the charts.
This PR fixes that by modifying mungeBarChartData() to consider the current 'mode' (current or previous) of the Explorer. 
- Fixes [AB#9990](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/9990) [AB#9998](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/9998)

9990 Preliminary restoration of  ACS previous (-2010) and current (-2020) bar charts

---

app/components/acs-bar.js
app/templates/explorer.hbs
app/utils/munge-bar-chart-data.js

This is a first pass of restoring all Decennial bar charts. Previously 2020 bar charts appeared without issue, but 2010 bar charts yielded errors and comparison area percentage did not appear in the charts.
This PR depends on #1027 being merged first.  #1027  fixes previous year bar charts by modifying mungeBarChartData() to consider the current 'mode' (current or previous) of the Explorer. 
This PR simply re-enables both previous and current year charts. 
- Fixes [AB#9997](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/9997) [AB#9967](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/9967)

9997 Preliminary restoration of  Decennial current (2020) and previous (2000) bar charts

---

app/components/acs-bar.js
app/topics-config/acs.js

styling issue.. top category label is cut off and text is tighter than category bars 
seems the chart is just stretched longer in the current app: 
The fix:
- Fixes [AB#5223](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/5223)
When Y-axis has more than 7 items, I have added 16px to the height per item over 7.

5223 chart resizing to fix label spacing

---

app/chart-config/acs/economic/index.js
app/chart-config/acs/economic/ratio-of-income-to-poverty-level.js
app/chart-config/acs/housing/gross-rent-grapi.js
app/chart-config/acs/housing/gross-rent.js
app/chart-config/acs/housing/index.js
app/topics-config/acs.js

We previously removed charts for certain topics according to a list charts required for the 2020 rework, but want to restore them now. 
This PR restores them and also updates them with 2020 schema changes.
- Fixes [AB#10029](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/10029)

10029 restore previous charts for certain topics 

---

app/components/map-utility-box.js
app/services/selection.js
app/styles/layouts/_l-default.scss
app/templates/components/map-utility-box.hbs
app/utils/fetch-selection-summary.js

Adds the summary totals to the map selection box.
- Along with a corresponding [pr in labs-factfinder-api](https://github.com/NYCPlanning/labs-factfinder-api/pull/199), completes [AB#5537](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/5537)

5537 Add the population and housing facts to the map selection box

---

app/components/population-pyramid.js
app/controllers/explorer.js
app/templates/explorer.hbs

Fixes [AB#9971](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/9971) Restores the ACS Sex and Age population pyramid chart for current year, and also wires it up to previous year data.

9971 restore 2020 pop pyramid chart

---

app/controllers/explorer.js
app/templates/explorer.hbs

The amount of time it takes for the user to receive UI feedback after clicking "All Topics" in the Select Topics dropdown is unacceptably long.  
This task is to give some sort of immediate UI feedback, such as a "loading" spinner, when the user clicks "All Topics". 
Ideally the spinner is in the large whitespace where the tables will eventually render 
- Fixes [AB#9994](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/9994)
When a user changes which topics are selected, it does not fetch any data.  The delay is simply how long it takes Ember to re-render the DOM.  When it needs to render 42 tables, that amount of time creeps up into multiple seconds.  Ember's built-in loading screen is built on the premise that it is waiting for a network request to …

9994 Display immediate UI feedback upon selecting "All Topics"

---

app/styles/layouts/_l-default.scss
app/templates/components/map-utility-box.hbs

This is just a small follow-up PR to [PR 1025](https://github.com/NYCPlanning/labs-factfinder/pull/1025) to incorporate some feedback from Erica.

5537 Add source and tweak styles for map utility box quick facts

---

app/templates/components/explorer/source-select-dropdown.hbs

Note to data selection dropdown to prompt users to use CDTA's instead of CDs to access ACD data for CDs
- Fixes [AB#11731](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/11731)
-

11731 note added to data selection dropdown

---

app/components/data-table.js

When copying and pasting the tables on PFF, the up and down arrows (svg elements) could not be copied correctly so an empty space  was substituted when pasted, which caused spreadsheets to interpret the input as a string rather than a number (or percent).
I replaced the deprecated `Document.execCommand()` with the Clipboard API. The API can be set to only copy text, avoiding the addition of empty spaces when copying PFF table data.
- Fixes [AB#5043](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/5043)
[Document/execCommand](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand)
[Clipboard_API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API)

5043 removed deprecated copy method and use clipboard api

---

app/templates/components/explorer/source-select-dropdown.hbs

updated task to remove red copy and change to black.
- Fixes [AB#11731](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/11731)

11731 changed font color for add'l copy to black (from red)

---

app/components/explorer/source-select-dropdown.js
app/styles/modules/components/explorer/source-select-dropdown.scss
app/templates/components/explorer/source-select-dropdown.hbs

- Only show ACS data warning message when community districts are the source.
- Add spacing above said warning
- Fixes [AB#12683](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/12683)
- Parent Story [AB#12660](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/12660)
- Implement a method on the component which checks whether the district ACS data warning should be shown, depending on whether the current source is a data district.
- Add 1rem top margin to paragraph

12683 district acs data dropdown warning

---

config/environment.js

The herokuapp.com URL for staging layers API is blocked by some firewalls so I'm temporarily switching back to the planninglabs.nyc URL for the same Heroku app. This should only affect staging deployments for PFF.

Change environment.js to use planninglabs.nyc staging domain for layers API

---

app/styles/app.scss
app/styles/modules/_m-spinner.scss
app/templates/components/acs-bar.hbs
app/templates/components/data-table-header-current.hbs
app/templates/components/data-table-header-previous.hbs
app/templates/components/horizontal-bar.hbs
app/templates/components/page-load-spinner.hbs
app/templates/explorer.hbs
app/templates/index.hbs
app/templates/loading.hbs

The lottie animation screen was causing issues in various places throughout PFF where loading times shorter than (approx) 2 seconds, making the screen appear to blink. Reverting back to the 3 dots loading screen restored expected "smoothness" when PFF is fetching new data.
- Fixes 
- [AB#13364](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/13364)
- Related 
- [AB#12726](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/12726)
- [PR where lottie animation was first implemented](https://github.com/NYCPlanning/labs-factfinder/pull/1079)

13364 revered lottie loading animation on most loading screens

---

app/templates/components/default-modal.hbs

Remove from the banner the note about 2016-2020 data being available in the archive
[AB#14578](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/14578)

remove banner text for archive note

---

app/templates/components/default-modal.hbs

Update copy of initial pop-up on opening the PFF
Closes #1121

issue/16067 Update copy homepage pop-up

---

app/templates/components/default-modal.hbs

[Issue 16067](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/16067)
[Workflow branch strategy](https://github.com/NYCPlanning/labs-factfinder/issues/1134)
- #### AFTER UPDATE IS FINISHED

1123/16067 PFF Updates: Copy Changes: modify post-update pop-up message

---

app/components/map-search.js
app/templates/components/map-search.hbs

Fixes an issue where when searching for a CDTA, the search and map does not yield a result.
- Along with [Factfinder API #291](https://github.com/NYCPlanning/labs-factfinder-api/pull/291) completes [Factfinder API Issue #289](https://github.com/NYCPlanning/labs-factfinder-api/issues/289)

289 Search results now include CDTAs

---

app/components/labs-ui/layer-group-toggle.js

Closes #1153.
Now when initializing or navigating back to the map, layer group toggles will reset to the default inactive state.

Set all layer groups to inactive on component init

---

app/table-config/acs/demographic/sex-and-age.js

Update variable for `Under 18 years`
- Closes #1175

1175 updated under 18 years data variable

---

app/components/map-search.js

Closes #1152.
~~Also updates start:local-api script~~

Remove address from map when closing out search

---

app/components/data-table-row-change.js
app/components/data-table-row-previous.js
app/templates/components/data-table-row-change.hbs
app/templates/components/data-table-row-previous.hbs

Closes #1173.
Removes row values from headers in previous and change over time datasets.

1173 Remove row header values staging

---

app/templates/components/data-table-row-change.hbs

for decennial data, change over time shouldn't appear for any of the regional groups in detailed race and ethnicity chart
- Closes #1172 
Some clarification from Pop on the requirements:

1172 hide change over time for detailed race and ethnicity

---

app/components/data-table-row-change.js
app/components/data-table-row-previous.js
app/templates/components/data-table-row-change.hbs
app/templates/components/data-table-row-previous.hbs

Closes #1173.
Removes row values from headers in previous and change over time datasets.

Remove values from header rows in Detailed Race and Ethnicity Section

---

app/templates/components/data-table-row-current.hbs
tests/integration/components/data-table-row-current-test.js

Adds logic to hide values in current tables

Hide values for row headers in Detailed Race and Ethnicity Section

---

app/templates/components/default-modal.hbs
app/topics-config/census.js

- updated popup with post pff update copy
- updated copy for detailed race and ethnicity label
- Closes #1123

1123 aggregated copy updates
